/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package util;

import Docs.IntegranteDoc;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author santi
 */
public class PanelIntegrante extends javax.swing.JPanel {

    IntegranteDoc integrante;
    /**
     * Creates new form PanelIntegrante
     */
    public PanelIntegrante(IntegranteDoc integrante) {
        
        initComponents();
        
        this.setOpaque(false);
        this.integrante = integrante;
        
        inicializar();
        
    }
    
    private void inicializar(){
    
        lblNombreIntegrante.setText(integrante.getNombre());
        lblInstrumento.setText(integrante.getInstrumento());
        
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("yyyy");
        String anioIngreso = integrante.getFechaIngreso().format(formato);
        
        lblFechaIngreso.setText(anioIngreso);
        
        if(!integrante.getEsActivo()){

            String anioEgreso = integrante.getFechaEgreso().format(formato);

            lblFechaEgreso.setText(anioEgreso);
            
        }
        else{
        
            lblFechaEgreso.setVisible(false);
            lblMiembroHasta.setVisible(false);
            
        }
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreIntegrante = new javax.swing.JLabel();
        lblInstrumento = new javax.swing.JLabel();
        lblFechaIngreso = new javax.swing.JLabel();
        lblMiembroDesde = new javax.swing.JLabel();
        lblMiembroHasta = new javax.swing.JLabel();
        lblFechaEgreso = new javax.swing.JLabel();

        lblNombreIntegrante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombreIntegrante.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreIntegrante.setText("Charly García");

        lblInstrumento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInstrumento.setForeground(new java.awt.Color(255, 255, 255));
        lblInstrumento.setText("Teclado");

        lblFechaIngreso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFechaIngreso.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaIngreso.setText("1978");

        lblMiembroDesde.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMiembroDesde.setForeground(new java.awt.Color(255, 255, 255));
        lblMiembroDesde.setText("Miembro desde:");

        lblMiembroHasta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMiembroHasta.setForeground(new java.awt.Color(255, 255, 255));
        lblMiembroHasta.setText("Dejó la banda en:");

        lblFechaEgreso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFechaEgreso.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaEgreso.setText("1978");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMiembroHasta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFechaEgreso)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMiembroDesde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFechaIngreso))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombreIntegrante)
                                .addGap(91, 91, 91)
                                .addComponent(lblInstrumento)))
                        .addContainerGap(263, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreIntegrante)
                    .addComponent(lblInstrumento))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaIngreso)
                    .addComponent(lblMiembroDesde))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaEgreso)
                    .addComponent(lblMiembroHasta))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFechaEgreso;
    private javax.swing.JLabel lblFechaIngreso;
    private javax.swing.JLabel lblInstrumento;
    private javax.swing.JLabel lblMiembroDesde;
    private javax.swing.JLabel lblMiembroHasta;
    private javax.swing.JLabel lblNombreIntegrante;
    // End of variables declaration//GEN-END:variables
}
