/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package util;

import DTO.AlbumDTO;
import DTO.UsuarioDTO;
import Docs.CancionDoc;
import Docs.FavoritoDoc;
import excepciones.NegocioException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class PanelCancionDesplegada extends javax.swing.JPanel {

    CancionDoc cancion = new CancionDoc();
    UsuarioDTO loggedUser = new UsuarioDTO();
    boolean esFav = false;
    /**
     * Creates new form PanelCancionDesplegada
     */
    public PanelCancionDesplegada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCancionEncontrada1 = new javax.swing.JPanel();
        imagenCancion3 = new util.ImagenPerfil();
        lblNombreCancion1 = new javax.swing.JLabel();
        lblNombreArtistaCancion1 = new javax.swing.JLabel();
        btnPlay1 = new util.BotonToggle();
        btnFavCancion1 = new util.BotonToggle();

        panelCancionEncontrada1.setBackground(new java.awt.Color(27, 26, 26));
        panelCancionEncontrada1.setMinimumSize(new java.awt.Dimension(750, 100));

        imagenCancion3.setImagen(new javax.swing.ImageIcon(getClass().getResource("/albums/Peperina.jpg"))); // NOI18N
        imagenCancion3.setPreferredSize(new java.awt.Dimension(50, 50));

        lblNombreCancion1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombreCancion1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCancion1.setText("Peperina");

        lblNombreArtistaCancion1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreArtistaCancion1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreArtistaCancion1.setText("Seru Giran");

        btnPlay1.setClickedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pause.png"))); // NOI18N
        btnPlay1.setNormalIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        btnPlay1.setPreferredSize(new java.awt.Dimension(28, 28));

        btnFavCancion1.setClickedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starClick.png"))); // NOI18N
        btnFavCancion1.setNormalIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N
        btnFavCancion1.setPreferredSize(new java.awt.Dimension(28, 28));
        btnFavCancion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavCancion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCancionEncontrada1Layout = new javax.swing.GroupLayout(panelCancionEncontrada1);
        panelCancionEncontrada1.setLayout(panelCancionEncontrada1Layout);
        panelCancionEncontrada1Layout.setHorizontalGroup(
            panelCancionEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancionEncontrada1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnPlay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(imagenCancion3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(panelCancionEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCancionEncontrada1Layout.createSequentialGroup()
                        .addComponent(lblNombreArtistaCancion1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblNombreCancion1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnFavCancion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        panelCancionEncontrada1Layout.setVerticalGroup(
            panelCancionEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancionEncontrada1Layout.createSequentialGroup()
                .addGroup(panelCancionEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCancionEncontrada1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnFavCancion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCancionEncontrada1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelCancionEncontrada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagenCancion3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCancionEncontrada1Layout.createSequentialGroup()
                                .addComponent(lblNombreCancion1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreArtistaCancion1))
                            .addGroup(panelCancionEncontrada1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnPlay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelCancionEncontrada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelCancionEncontrada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFavCancion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavCancion1ActionPerformed


            FavoritoDoc favNuevo = new FavoritoDoc();

            List<CancionDoc> favoritas = new ArrayList<>();

            if(loggedUser.getFavoritos()!= null){

                favNuevo = loggedUser.getFavoritos();

                favoritas = favNuevo.getCanciones();

            }

            favoritas.add(cancion);

            favNuevo.setCanciones(favoritas);

            loggedUser.setFavoritos(favNuevo);

    }//GEN-LAST:event_btnFavCancion1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.BotonToggle btnFavCancion1;
    private util.BotonToggle btnPlay1;
    private util.ImagenPerfil imagenCancion3;
    private javax.swing.JLabel lblNombreArtistaCancion1;
    private javax.swing.JLabel lblNombreCancion1;
    private javax.swing.JPanel panelCancionEncontrada1;
    // End of variables declaration//GEN-END:variables
}
