/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames;

import DTO.AlbumDTO;
import Docs.CancionDoc;
import excepciones.NegocioException;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import util.PanelAlbumDesplegado;
import util.PanelCancionDesplegada;

/**
 *
 * @author carli
 */
public class PanelHome extends javax.swing.JPanel {

    FrmPrincipal frmPrincipal;

    /**
     * Creates new form Prueba1
     */
    public PanelHome(FrmPrincipal frmPrincipal) {
        initComponents();
        this.frmPrincipal = frmPrincipal;
        
        panelAlbumes.setLayout(new FlowLayout());
        panelCanciones.setLayout(new FlowLayout());
        buscarAlbumes();
        buscarCanciones();
        
        this.revalidate();
        this.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelAlbumes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelCanciones = new javax.swing.JPanel();
        panelCancion3 = new javax.swing.JPanel();
        numCancion3 = new javax.swing.JLabel();
        imagenCancion3 = new util.ImagenPerfil();
        lblNombreCancion3 = new javax.swing.JLabel();
        lblNombreArtistaCancion3 = new javax.swing.JLabel();
        play3 = new util.BotonToggle();
        btnfavoritoCancion3 = new util.BotonToggle();

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left.png"))); // NOI18N
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton21)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jButton21)
                .addGap(14, 14, 14))
        );

        jPanel15.add(jPanel16);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/albums/Peperina.jpg"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel15.add(jButton3);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/albums/Peperina.jpg"))); // NOI18N
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel15.add(jButton22);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/albums/Peperina.jpg"))); // NOI18N
        jButton23.setBorderPainted(false);
        jButton23.setContentAreaFilled(false);
        jButton23.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel15.add(jButton23);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/albums/Peperina.jpg"))); // NOI18N
        jButton24.setBorderPainted(false);
        jButton24.setContentAreaFilled(false);
        jButton24.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel15.add(jButton24);

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/albums/Peperina.jpg"))); // NOI18N
        jButton25.setBorderPainted(false);
        jButton25.setContentAreaFilled(false);
        jButton25.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel15.add(jButton25);

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/albums/Peperina.jpg"))); // NOI18N
        jButton26.setBorderPainted(false);
        jButton26.setContentAreaFilled(false);
        jButton26.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel15.add(jButton26);

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/right.png"))); // NOI18N
        jButton27.setBorderPainted(false);
        jButton27.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jButton27)
                .addGap(12, 12, 12))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jButton27)
                .addGap(15, 15, 15))
        );

        jPanel15.add(jPanel17);

        setBackground(new java.awt.Color(27, 26, 26));

        jPanel2.setBackground(new java.awt.Color(27, 26, 26));

        jLabel1.setBackground(new java.awt.Color(27, 26, 26));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novedades.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 668, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nuevos Albumes");

        jLabel5.setText(" ");

        panelAlbumes.setBackground(new java.awt.Color(27, 26, 26));
        panelAlbumes.setPreferredSize(new java.awt.Dimension(750, 850));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nuevas Canciones");

        panelCanciones.setBackground(new java.awt.Color(27, 26, 26));
        panelCanciones.setPreferredSize(new java.awt.Dimension(750, 500));

        panelCancion3.setBackground(new java.awt.Color(27, 26, 26));
        panelCancion3.setMinimumSize(new java.awt.Dimension(750, 100));

        numCancion3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numCancion3.setForeground(new java.awt.Color(255, 255, 255));
        numCancion3.setText("01");

        imagenCancion3.setImagen(new javax.swing.ImageIcon(getClass().getResource("/albums/Peperina.jpg"))); // NOI18N
        imagenCancion3.setPreferredSize(new java.awt.Dimension(50, 50));

        lblNombreCancion3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombreCancion3.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCancion3.setText("Peperina");

        lblNombreArtistaCancion3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreArtistaCancion3.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreArtistaCancion3.setText("Seru Giran");

        play3.setClickedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pause.png"))); // NOI18N
        play3.setNormalIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        play3.setPreferredSize(new java.awt.Dimension(28, 28));

        btnfavoritoCancion3.setClickedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starClick.png"))); // NOI18N
        btnfavoritoCancion3.setNormalIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N
        btnfavoritoCancion3.setPreferredSize(new java.awt.Dimension(28, 28));

        javax.swing.GroupLayout panelCancion3Layout = new javax.swing.GroupLayout(panelCancion3);
        panelCancion3.setLayout(panelCancion3Layout);
        panelCancion3Layout.setHorizontalGroup(
            panelCancion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancion3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(numCancion3)
                .addGap(18, 18, 18)
                .addComponent(play3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(imagenCancion3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(panelCancion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCancion3)
                    .addComponent(lblNombreArtistaCancion3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnfavoritoCancion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        panelCancion3Layout.setVerticalGroup(
            panelCancion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancion3Layout.createSequentialGroup()
                .addGroup(panelCancion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCancion3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelCancion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagenCancion3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCancion3Layout.createSequentialGroup()
                                .addComponent(lblNombreCancion3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreArtistaCancion3))))
                    .addGroup(panelCancion3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelCancion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(play3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numCancion3)))
                    .addGroup(panelCancion3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnfavoritoCancion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCancionesLayout = new javax.swing.GroupLayout(panelCanciones);
        panelCanciones.setLayout(panelCancionesLayout);
        panelCancionesLayout.setHorizontalGroup(
            panelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancionesLayout.createSequentialGroup()
                .addGap(1728, 1728, 1728)
                .addComponent(panelCancion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCancionesLayout.setVerticalGroup(
            panelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancionesLayout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addComponent(panelCancion3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(panelAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(789, 789, 789))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addGap(572, 572, 572)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panelCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void buscarAlbumes(){

        //Eliminamos los albumes previamente desplegadas si existen        
        
        //Eliminamos los albumes que se estén mostrando en pantalla
        panelAlbumes.removeAll();
        
        int counter = 0;
        
        //Buscamos los albumes con el filtro especificado
        try {
            
            List<AlbumDTO> albumes = new ArrayList<>();


                    albumes = frmPrincipal.albumNegocio.obtenerAlbumesPorBusqueda("", frmPrincipal.getLoggedUser());

            
            //Si nos regresa datos vacíos, terminamos ejecución

            if(albumes == null)
                return;

            Collections.shuffle(albumes);
            
            //Iteramos por cada album que nos regresa
            for(AlbumDTO album : albumes){
                
                    PanelAlbumDesplegado panel = new PanelAlbumDesplegado(frmPrincipal, this, album, frmPrincipal.getLoggedUser(), frmPrincipal.usuarioNegocio, frmPrincipal.albumNegocio);
                    
                    //Si ya están desplegadas más de 6 albumes terminamos la ejecución, ya que ya no hay espacio para mostrar
                    if(counter >= 3)
                        return;
                    
                    panelAlbumes.add(panel);
                    
                    counter++;
                    
            }
                
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar los albumes " + ex);
        }
        
    }    
    public void buscarCanciones(){

        //Eliminamos los albumes previamente desplegadas si existen        
        
        //Eliminamos los albumes que se estén mostrando en pantalla
        panelCanciones.removeAll();
        
        int counter = 0;
        
        //Buscamos los albumes con el filtro especificado
        try {
            
            List<AlbumDTO> albumes = new ArrayList<>();


                    albumes = frmPrincipal.albumNegocio.obtenerCancionesPorBusqueda("", frmPrincipal.getLoggedUser());

            
            //Si nos regresa datos vacíos, terminamos ejecución

            if(albumes == null)
                return;

            Collections.shuffle(albumes);
            
            //Iteramos por cada album que nos regresa
            for(AlbumDTO album : albumes){
                
                for(CancionDoc cancion : album.getCanciones()){
                    PanelCancionDesplegada panel = new PanelCancionDesplegada(frmPrincipal, this, cancion, album, frmPrincipal.getLoggedUser(), frmPrincipal.usuarioNegocio);
                    
                    //Si ya están desplegadas más de 6 albumes terminamos la ejecución, ya que ya no hay espacio para mostrar
                    if(counter >= 6)
                        return;
                    
                    panelCanciones.add(panel);
                    
                    counter++;
                }
            }
                
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar los albumes " + ex);
        }
        
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.BotonToggle btnfavoritoCancion3;
    private util.ImagenPerfil imagenCancion3;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNombreArtistaCancion3;
    private javax.swing.JLabel lblNombreCancion3;
    private javax.swing.JLabel numCancion3;
    private javax.swing.JPanel panelAlbumes;
    private javax.swing.JPanel panelCancion3;
    private javax.swing.JPanel panelCanciones;
    private util.BotonToggle play3;
    // End of variables declaration//GEN-END:variables
}
