/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames;

import Conexion.ConexionDB;
import DAO.GeneroDAO;
import DTO.AlbumDTO;
import DTO.ArtistaDTO;
import DTO.FiltroMusicaDTO;
import DTO.GeneroDTO;
import Docs.CancionDoc;
import InterfacesDAO.IConexionDB;
import InterfacesDAO.IGeneroDAO;
import InterfacesNegocio.IGeneroNegocio;
import Negocio.GeneroNegocio;
import excepciones.NegocioException;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.time.Clock;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import util.ImagenPerfil;
import util.PanelAlbumDesplegado;
import util.PanelArtistaDesplegado;
import util.PanelCancionDesplegada;

/**
 *
 * @author carli
 */
public class PanelBusqueda extends javax.swing.JPanel {
    
    FrmPrincipal frmPrincipal;
    
    //Canciones
    List<CancionDoc> cancionesDesplegadas = new ArrayList<>();
    
    //Albumes
    List<AlbumDTO> albumesDesplegados = new ArrayList<>();
    
    //Artistas
    List<ArtistaDTO> artistasDesplegados = new ArrayList<>();
    
    FiltroMusicaDTO filtroMusica = null;

    

    /**
     * Creates new form Prueba1
     */
    public PanelBusqueda(FrmPrincipal frmPrincipal) {
        initComponents();
        
        this.frmPrincipal = frmPrincipal;
        
        setDefaultTextAndAddFocusListener(buscador, "Buscar...");

        checkFechaLanzamiento.setOpaque(false);

        
        this.revalidate();
        this.repaint();
    }
    
    public void setFiltroMusica(FiltroMusicaDTO filtro){
    
        this.filtroMusica = filtro;
        
    }

    private void setDefaultTextAndAddFocusListener(javax.swing.JTextField campoTexto, String textoDefault) {
        campoTexto.setText(textoDefault);
        campoTexto.setForeground(Color.GRAY);
        campoTexto.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (campoTexto.getText().equals(textoDefault)) {
                    campoTexto.setText("");
                    campoTexto.setForeground(Color.BLACK);
                    campoTexto.setBorder(BorderFactory.createLineBorder(new Color(135, 116, 249), 4));
                }
            }
            
            @Override
            public void focusLost(FocusEvent e) {
                if (campoTexto.getText().isEmpty()) {
                    campoTexto.setText(textoDefault);
                    campoTexto.setForeground(Color.GRAY);
                    campoTexto.setBorder(BorderFactory.createLineBorder(Color.WHITE, 2));
                    
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buscador = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        checkFechaLanzamiento = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        panelCanciones = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelArtistas = new javax.swing.JPanel();
        lblArtistas = new javax.swing.JLabel();
        lblCanciones = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        panelAlbumes = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left.png"))); // NOI18N
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton21)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jButton21)
                .addGap(14, 14, 14))
        );

        jPanel15.add(jPanel16);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/albums/Peperina.jpg"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel15.add(jButton3);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/albums/Peperina.jpg"))); // NOI18N
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel15.add(jButton22);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/albums/Peperina.jpg"))); // NOI18N
        jButton23.setBorderPainted(false);
        jButton23.setContentAreaFilled(false);
        jButton23.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel15.add(jButton23);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/albums/Peperina.jpg"))); // NOI18N
        jButton24.setBorderPainted(false);
        jButton24.setContentAreaFilled(false);
        jButton24.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel15.add(jButton24);

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/albums/Peperina.jpg"))); // NOI18N
        jButton25.setBorderPainted(false);
        jButton25.setContentAreaFilled(false);
        jButton25.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel15.add(jButton25);

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/albums/Peperina.jpg"))); // NOI18N
        jButton26.setBorderPainted(false);
        jButton26.setContentAreaFilled(false);
        jButton26.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel15.add(jButton26);

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/right.png"))); // NOI18N
        jButton27.setBorderPainted(false);
        jButton27.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jButton27)
                .addGap(12, 12, 12))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jButton27)
                .addGap(15, 15, 15))
        );

        jPanel15.add(jPanel17);

        setBackground(new java.awt.Color(27, 26, 26));

        jPanel2.setBackground(new java.awt.Color(27, 26, 26));

        jPanel6.setBackground(new java.awt.Color(27, 26, 26));
        jPanel6.setPreferredSize(new java.awt.Dimension(1500, 261));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Busqueda");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N

        buscador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buscador.setForeground(new java.awt.Color(204, 204, 204));
        buscador.setText("Search...");
        buscador.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        buscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorActionPerformed(evt);
            }
        });
        buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscadorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscadorKeyReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filtros.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        checkFechaLanzamiento.setText("Buscar por fecha de lanzamiento");
        checkFechaLanzamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFechaLanzamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel8)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkFechaLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(checkFechaLanzamiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buscador))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(27, 27, 27))))
        );

        jPanel3.setBackground(new java.awt.Color(27, 26, 26));

        panelCanciones.setBackground(new java.awt.Color(27, 26, 26));
        panelCanciones.setPreferredSize(new java.awt.Dimension(750, 850));
        jPanel3.add(panelCanciones);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("         ");
        jPanel3.add(jLabel7);

        panelArtistas.setBackground(new java.awt.Color(27, 26, 26));
        panelArtistas.setPreferredSize(new java.awt.Dimension(750, 850));
        jPanel3.add(panelArtistas);

        lblArtistas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblArtistas.setForeground(new java.awt.Color(255, 255, 255));
        lblArtistas.setText("Artistas");
        lblArtistas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblArtistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblArtistasMouseClicked(evt);
            }
        });

        lblCanciones.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCanciones.setForeground(new java.awt.Color(255, 255, 255));
        lblCanciones.setText("Canciones");
        lblCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancionesMouseClicked(evt);
            }
        });

        jPanel43.setBackground(new java.awt.Color(27, 26, 26));
        jPanel43.setPreferredSize(new java.awt.Dimension(1275, 100));

        jPanel44.setBackground(new java.awt.Color(27, 26, 26));
        jPanel44.setForeground(new java.awt.Color(255, 255, 255));
        jPanel44.setToolTipText("");
        jPanel44.setPreferredSize(new java.awt.Dimension(200, 130));

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel43.add(jPanel44);

        jLabel25.setText(" ");
        jPanel43.add(jLabel25);

        jPanel45.setBackground(new java.awt.Color(27, 26, 26));
        jPanel45.setForeground(new java.awt.Color(255, 255, 255));
        jPanel45.setToolTipText("");
        jPanel45.setPreferredSize(new java.awt.Dimension(200, 130));

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel43.add(jPanel45);

        jLabel26.setText(" ");
        jPanel43.add(jLabel26);

        jPanel46.setBackground(new java.awt.Color(27, 26, 26));
        jPanel46.setForeground(new java.awt.Color(255, 255, 255));
        jPanel46.setToolTipText("");
        jPanel46.setPreferredSize(new java.awt.Dimension(200, 130));

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel43.add(jPanel46);

        jLabel27.setText(" ");
        jPanel43.add(jLabel27);

        jPanel47.setBackground(new java.awt.Color(27, 26, 26));
        jPanel47.setForeground(new java.awt.Color(255, 255, 255));
        jPanel47.setToolTipText("");
        jPanel47.setPreferredSize(new java.awt.Dimension(200, 130));

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel43.add(jPanel47);

        jLabel6.setText(" ");
        jPanel43.add(jLabel6);

        jPanel48.setBackground(new java.awt.Color(27, 26, 26));
        jPanel48.setForeground(new java.awt.Color(255, 255, 255));
        jPanel48.setToolTipText("");
        jPanel48.setPreferredSize(new java.awt.Dimension(200, 130));

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel43.add(jPanel48);

        jLabel28.setText(" ");
        jPanel43.add(jLabel28);

        jPanel49.setBackground(new java.awt.Color(27, 26, 26));
        jPanel49.setForeground(new java.awt.Color(255, 255, 255));
        jPanel49.setToolTipText("");
        jPanel49.setPreferredSize(new java.awt.Dimension(200, 130));

        javax.swing.GroupLayout jPanel49Layout = new javax.swing.GroupLayout(jPanel49);
        jPanel49.setLayout(jPanel49Layout);
        jPanel49Layout.setHorizontalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel49Layout.setVerticalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel43.add(jPanel49);

        panelAlbumes.setBackground(new java.awt.Color(27, 26, 26));

        jLabel12.setText(" ");
        panelAlbumes.add(jLabel12);

        jLabel13.setText(" ");
        panelAlbumes.add(jLabel13);

        jLabel14.setText(" ");
        panelAlbumes.add(jLabel14);

        jLabel15.setText(" ");
        panelAlbumes.add(jLabel15);

        jLabel16.setText(" ");
        panelAlbumes.add(jLabel16);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Albumes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1780, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblCanciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblArtistas)
                .addGap(442, 442, 442))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAlbumes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel24)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArtistas)
                    .addComponent(lblCanciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(912, 912, 912))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorActionPerformed

    }//GEN-LAST:event_buscadorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           
        panelAlbumes.removeAll();
        panelCanciones.removeAll();
        panelArtistas.removeAll();
        
        DialogFiltros popup = new DialogFiltros(frmPrincipal,this, frmPrincipal.generoNegocio, frmPrincipal.getLoggedUser(), filtroMusica); // 'frmPrincipal' is the parent frame
        popup.setLocationRelativeTo(frmPrincipal);

        popup.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadorKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_buscadorKeyPressed

    public void buscarCanciones(String filtro){
    
        //Eliminamos las canciones previamente desplegadas si existen        
        if(!cancionesDesplegadas.isEmpty())
            cancionesDesplegadas.clear();
        
        //Eliminamos las canciones que se estén mostrando en pantalla
        panelCanciones.removeAll();
        
        int counter = 0;
        
        //Buscamos las canciones con el filtro especificado
        try {
            
            List<AlbumDTO> albumes = new ArrayList<>();
            
            
            if(filtroMusica == null)
                    
                if(checkFechaLanzamiento.isSelected())
                    albumes = frmPrincipal.albumNegocio.obtenerCancionesPorFecha(filtro, frmPrincipal.getLoggedUser());
                
                else
                    albumes = frmPrincipal.albumNegocio.obtenerCancionesPorBusqueda(filtro, frmPrincipal.getLoggedUser());
            
            else

                if(checkFechaLanzamiento.isSelected())
                    albumes = frmPrincipal.albumNegocio.obtenerCancionesPorFechaGeneros(filtro, filtroMusica.getGeneros());
                
                else
                    albumes = frmPrincipal.albumNegocio.obtenerCancionesPorBusquedaGeneros(filtro, filtroMusica.getGeneros());
            
            //Si nos regresa datos vacíos, terminamos ejecución
            if(albumes == null)
                return;
            
            //Iteramos por cada album que nos regresa
            for(AlbumDTO album : albumes){
                
                //Iteramos por cada canción dentro del album
                for(CancionDoc cancion : album.getCanciones()){
                    
                    PanelCancionDesplegada panel = new PanelCancionDesplegada(frmPrincipal,this, cancion, album, frmPrincipal.getLoggedUser(), frmPrincipal.usuarioNegocio);
                    //Si ya están desplegadas más de 9 canciones terminamos la ejecución, ya que ya no hay espacio para mostrar
                    if(counter >= 9)
                        return;
                    
                    //Agregamos la canción desplegada en la lista de canciones
                    cancionesDesplegadas.add(cancion);
                    
                    panelCanciones.add(panel);
                    
                    counter++;
                    
                }
                
            }
                
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar las canciones " + ex);
        }
        
        
    }
    
    public void buscarAlbumes(String filtro){

        //Eliminamos los albumes previamente desplegadas si existen        
        if(!albumesDesplegados.isEmpty())
            albumesDesplegados.clear();
        
        //Eliminamos los albumes que se estén mostrando en pantalla
        panelAlbumes.removeAll();
        
        int counter = 0;
        
        //Buscamos los albumes con el filtro especificado
        try {
            
            List<AlbumDTO> albumes = new ArrayList<>();
            
            if(filtroMusica == null)
                    
                if(checkFechaLanzamiento.isSelected())
                    albumes = frmPrincipal.albumNegocio.obtenerAlbumesPorFecha(filtro, frmPrincipal.getLoggedUser());
                
                else
                    albumes = frmPrincipal.albumNegocio.obtenerAlbumesPorBusqueda(filtro, frmPrincipal.getLoggedUser());
            
            else

                if(checkFechaLanzamiento.isSelected())
                    albumes = frmPrincipal.albumNegocio.obtenerAlbumesPorFechaGeneros(filtro, filtroMusica.getGeneros());
                
                else
                    albumes = frmPrincipal.albumNegocio.obtenerAlbumesPorBusquedaGeneros(filtro, filtroMusica.getGeneros());
            
            //Si nos regresa datos vacíos, terminamos ejecución
            if(albumes == null)
                return;
            
            //Iteramos por cada album que nos regresa
            for(AlbumDTO album : albumes){
                
                    PanelAlbumDesplegado panel = new PanelAlbumDesplegado(frmPrincipal, album, frmPrincipal.getLoggedUser(), frmPrincipal.usuarioNegocio, frmPrincipal.albumNegocio);
                    
                    //Si ya están desplegadas más de 6 albumes terminamos la ejecución, ya que ya no hay espacio para mostrar
                    if(counter >= 6)
                        return;
              
                    //Agregamos el album desplegado en la lista de albumes
                    albumesDesplegados.add(album);
                    

                    panelAlbumes.add(panel);
                    
                    counter++;
                    
            }
                
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar los albumes " + ex);
        }
        
    }    
    
    public void buscarArtistas(String filtro){
        
        //Eliminamos los albumes previamente desplegadas si existen        
        if(!artistasDesplegados.isEmpty())
            artistasDesplegados.clear();
        
        //Eliminamos los albumes que se estén mostrando en pantalla
        panelArtistas.removeAll();
        
        int counter = 0;
        
        //Buscamos los albumes con el filtro especificado
        try {
            
            List<ArtistaDTO> artistas = new ArrayList<>();
            
            if(filtroMusica == null)
                artistas = frmPrincipal.artistaNegocio.obtenerArtistasPorBusqueda(filtro, frmPrincipal.getLoggedUser());
            else
                artistas = frmPrincipal.artistaNegocio.obtenerArtistasPorBusquedaGeneros(filtro, filtroMusica.getGeneros());
            
            
            //Si nos regresa datos vacíos, terminamos ejecución
            if(artistas == null)
                return;
            
            //Iteramos por cada album que nos regresa
            for(ArtistaDTO artista : artistas){
                
                    PanelArtistaDesplegado panel = new PanelArtistaDesplegado(frmPrincipal, artista, frmPrincipal.getLoggedUser(), frmPrincipal.usuarioNegocio, frmPrincipal.artistaNegocio);
                    
                    //Si ya están desplegadas más de 6 albumes terminamos la ejecución, ya que ya no hay espacio para mostrar
                    if(counter >= 6)
                        return;
              
                    //Agregamos el album desplegado en la lista de albumes
                    artistasDesplegados.add(artista);
                    

                    panelArtistas.add(panel);
                    
                    counter++;
                    
            }
                
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar los artistas " + ex);
        }
        
    }
    
    private void buscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadorKeyReleased
    
        if(buscador.getText().equals("")){
         
            panelAlbumes.removeAll();
            panelCanciones.removeAll();
            panelArtistas.removeAll();
            
            this.revalidate();
            this.repaint();
            return;
            
        }
        
        if(buscador.getText().equals("@all")){
         
            buscarCanciones("");
            buscarAlbumes("");
            buscarArtistas("");
            
            this.revalidate();
            this.repaint();
            return;
            
        }
            
        if(filtroMusica != null){
            
            if(filtroMusica.getAlbumes())
                buscarAlbumes(buscador.getText());
            
            if(filtroMusica.getCanciones())
                buscarCanciones(buscador.getText());
            
            if(filtroMusica.getArtistas())
                buscarArtistas(buscador.getText());

            this.revalidate();
            this.repaint();
        
        }
        else{
        
            buscarCanciones(buscador.getText());
            buscarAlbumes(buscador.getText());
            buscarArtistas(buscador.getText());

            this.revalidate();
            this.repaint();
        
        
        }
            
        
    }//GEN-LAST:event_buscadorKeyReleased

    private void checkFechaLanzamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFechaLanzamientoActionPerformed
        // TODO add your handling code here:
        
        if(filtroMusica != null)
            if(filtroMusica.getArtistas()){
            
                 JOptionPane.showMessageDialog(this, "No se puede buscar por fecha de lanzamiento cuando estás filtrando artistas");
                 checkFechaLanzamiento.setSelected(false);
                
            }

        
    }//GEN-LAST:event_checkFechaLanzamientoActionPerformed

    private void lblCancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancionesMouseClicked
        // TODO add your handling code here:
        frmPrincipal.pintarPanelPrincipal(new PanelCanciones(frmPrincipal, buscador.getText(), filtroMusica, checkFechaLanzamiento.isSelected()));
    }//GEN-LAST:event_lblCancionesMouseClicked

    private void lblArtistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArtistasMouseClicked
        // TODO add your handling code here:
//        frmPrincipal.pintarPanelPrincipal(new PanelArtistas(frmPrincipal, buscador.getText(), filtroMusica, checkFechaLanzamiento.isSelected()));
    }//GEN-LAST:event_lblArtistasMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscador;
    private javax.swing.JCheckBox checkFechaLanzamiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblArtistas;
    private javax.swing.JLabel lblCanciones;
    private javax.swing.JPanel panelAlbumes;
    private javax.swing.JPanel panelArtistas;
    private javax.swing.JPanel panelCanciones;
    // End of variables declaration//GEN-END:variables
}
