/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames;

/**
 *
 * @author carli
 */
public class PanelFavoritos extends javax.swing.JPanel {

    FrmPrincipal frmPrincipal;

    /**
     * Creates new form Prueba1
     */
    public PanelFavoritos(FrmPrincipal frmPrincipal) {
        initComponents();
        this.frmPrincipal = frmPrincipal;
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAlbumesFav = new javax.swing.JButton();
        btnArtistasFav = new javax.swing.JButton();
        btnCancionesFav = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(27, 26, 26));

        jPanel1.setBackground(new java.awt.Color(27, 26, 26));

        btnAlbumesFav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AlbumesFavoritos.png"))); // NOI18N
        btnAlbumesFav.setBorderPainted(false);
        btnAlbumesFav.setContentAreaFilled(false);
        btnAlbumesFav.setPreferredSize(new java.awt.Dimension(483, 309));
        btnAlbumesFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlbumesFavActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlbumesFav);

        btnArtistasFav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/artistasFavoritos.png"))); // NOI18N
        btnArtistasFav.setBorderPainted(false);
        btnArtistasFav.setContentAreaFilled(false);
        btnArtistasFav.setPreferredSize(new java.awt.Dimension(483, 309));
        btnArtistasFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtistasFavActionPerformed(evt);
            }
        });
        jPanel1.add(btnArtistasFav);

        btnCancionesFav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancionesfavoritos.png"))); // NOI18N
        btnCancionesFav.setBorderPainted(false);
        btnCancionesFav.setContentAreaFilled(false);
        btnCancionesFav.setPreferredSize(new java.awt.Dimension(483, 309));
        btnCancionesFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancionesFavActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancionesFav);

        jPanel2.setBackground(new java.awt.Color(27, 26, 26));

        jPanel3.setBackground(new java.awt.Color(27, 26, 26));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Favoritos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel2)
                .addGap(927, 927, 927)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addGap(296, 296, 296))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jLabel2))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addGap(85, 85, 85))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlbumesFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlbumesFavActionPerformed
        frmPrincipal.pintarPanelPrincipal(new PanelAlbumesFavoritos(frmPrincipal));
    }//GEN-LAST:event_btnAlbumesFavActionPerformed

    private void btnCancionesFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancionesFavActionPerformed

        frmPrincipal.pintarPanelPrincipal(new PanelCancionesFavoritas(frmPrincipal));
    }//GEN-LAST:event_btnCancionesFavActionPerformed

    private void btnArtistasFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtistasFavActionPerformed
        // TODO add your handling code here:
        frmPrincipal.pintarPanelPrincipal(new PanelArtistasFavoritos(frmPrincipal, this));
    }//GEN-LAST:event_btnArtistasFavActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlbumesFav;
    private javax.swing.JButton btnArtistasFav;
    private javax.swing.JButton btnCancionesFav;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
